const assert = require('node:assert/strict');
const { correlateEvent } = require('../dist/pipeline/correlation-engine');
const { canCorrelateWithTerminalIncident } = require('../dist/pipeline/webhook-event-policy');

const org = '00000000-0000-4000-8000-000000000001';
const fail = { id: '00000000-0000-4000-8000-000000000011', event: { eventId: 'evt_fail', eventType: 'payment.failed', occurredAt: '2026-08-22T00:00:00.000Z', receivedAt: '2026-08-22T00:00:01.000Z', orderId: 'order_a', amountPaise: 1000, currency: 'INR', providerData: {} }, enrichment: { gatewayHealthScore: 1, crossBorderFlag: false } };
const initial = correlateEvent(fail, [], org, () => '00000000-0000-4000-8000-000000000100');
assert.equal(initial.created, true);
assert.equal(initial.incident.status, 'OPEN');
const partial = { id: '00000000-0000-4000-8000-000000000012', event: { eventId: 'evt_partial', eventType: 'payment.captured', occurredAt: '2026-08-22T00:05:00.000Z', receivedAt: '2026-08-22T00:05:01.000Z', orderId: 'order_a', amountPaise: 300, currency: 'INR', providerData: {} }, enrichment: null };
const afterPartial = correlateEvent(partial, [{ incident: initial.incident, events: [fail] }], org);
assert.equal(afterPartial.incident.status, 'MONITORING');
assert.equal(afterPartial.incident.remainingAmountPaise, 700);
const full = { id: '00000000-0000-4000-8000-000000000013', event: { ...partial.event, eventId: 'evt_full', occurredAt: '2026-08-22T00:10:00.000Z', amountPaise: 700 }, enrichment: null };
const afterFull = correlateEvent(full, [{ incident: afterPartial.incident, events: [fail, partial] }], org);
assert.equal(afterFull.incident.status, 'RESOLVED');
const dispute = { id: '00000000-0000-4000-8000-000000000014', event: { ...fail.event, eventId: 'evt_dispute', eventType: 'payment.dispute.created' }, enrichment: null };
const disputed = correlateEvent(dispute, [{ incident: initial.incident, events: [fail] }], org);
assert.equal(disputed.incident.status, 'DISPUTE_OPENED');
assert.equal(disputed.incident.riskTier, 'CRITICAL');
const underReview = { id: '00000000-0000-4000-8000-000000000016', event: { ...fail.event, eventId: 'evt_under_review', eventType: 'payment.dispute.under_review' }, enrichment: null };
const underReviewResult = correlateEvent(underReview, [{ incident: initial.incident, events: [fail] }], org);
assert.equal(underReviewResult.incident.status, 'DISPUTE_OPENED');
assert.equal(underReviewResult.incident.riskTier, 'CRITICAL');
assert.equal(canCorrelateWithTerminalIncident('payment.dispute.under_review'), true, 'durable candidate lookup must include terminal incidents for every dispute-opening event');
assert.equal(canCorrelateWithTerminalIncident('payment.dispute.action_required'), true, 'durable candidate lookup must include terminal incidents for action-required disputes');
const early = { id: '00000000-0000-4000-8000-000000000015', event: { ...partial.event, eventId: 'evt_early', occurredAt: '2026-08-21T23:59:00.000Z', amountPaise: 1000 }, enrichment: null };
const ignored = correlateEvent(early, [{ incident: initial.incident, events: [fail] }], org);
assert.equal(ignored.incident.status, 'OPEN');
assert.equal(ignored.reason, 'recovery_outside_window_or_precedes_risk');
const resolvedDispute = correlateEvent(dispute, [{ incident: afterFull.incident, events: [fail, partial, full] }], org);
assert.equal(resolvedDispute.incident.id, afterFull.incident.id);
assert.equal(resolvedDispute.incident.status, 'DISPUTE_OPENED');
const lateCapture = correlateEvent(full, [{ incident: afterFull.incident, events: [fail, partial, full] }], org);
assert.equal(lateCapture.incident.status, 'RESOLVED');
assert.equal(lateCapture.reason, 'recovery_has_no_amount');
const dismissed = { ...initial.incident, status: 'DISMISSED' };
const dismissedPartial = correlateEvent(partial, [{ incident: dismissed, events: [fail] }], org);
assert.equal(dismissedPartial.incident.status, 'MONITORING');
console.log('Agentic MVP correlation checks passed.');
