import nodemailer, { SentMessageInfo, Transporter } from 'nodemailer';
import { RuntimeConfig } from '../../config/config';

export type EmailSendResult =
  | { kind: 'accepted'; messageId: string; acceptedCount: number; rejectedCount: number; response: string }
  | { kind: 'rejected'; messageId: string | null; response: string };

/**
 * SMTP is deliberately isolated here: recipients, headers and URLs come from
 * deterministic server-side inputs, never a model response or browser call.
 */
export class RecoveryEmailAdapter {
  private transporter: Transporter | undefined;

  constructor(private readonly config: NonNullable<RuntimeConfig['smtp']>) {}

  async verify(): Promise<void> {
    await this.getTransporter().verify();
  }

  async close(): Promise<void> {
    this.transporter?.close();
    this.transporter = undefined;
  }

  async send(input: { to: string; paymentLinkUrl: string; incidentId: string; subject: string; copyIntent: string }): Promise<EmailSendResult> {
    const recipient = safeEmail(input.to, 'recipient');
    const url = safeRazorpayUrl(input.paymentLinkUrl);
    const info = await this.getTransporter().sendMail({
      from: this.config.from,
      to: recipient,
      subject: boundedText(input.subject, 160, 'Email subject'),
      text: renderText(input.copyIntent, url),
      html: renderHtml(input.copyIntent, url),
      headers: { 'X-PayScope-Incident': input.incidentId },
    }) as SentMessageInfo;
    const accepted = Array.isArray(info.accepted) ? info.accepted.length : 0;
    const rejected = Array.isArray(info.rejected) ? info.rejected.length : 0;
    const messageId = typeof info.messageId === 'string' && info.messageId ? info.messageId.slice(0, 320) : null;
    const response = typeof info.response === 'string' ? redactSmtpResponse(info.response) : '';
    if (!accepted || rejected) return { kind: 'rejected', messageId, response };
    return { kind: 'accepted', messageId: messageId ?? '', acceptedCount: accepted, rejectedCount: rejected, response };
  }

  private getTransporter(): Transporter {
    if (this.transporter) return this.transporter;
    this.transporter = nodemailer.createTransport({
      pool: true,
      host: this.config.host,
      port: this.config.port,
      secure: this.config.secure,
      requireTLS: !this.config.secure,
      auth: { user: this.config.user, pass: this.config.pass },
      maxConnections: this.config.maxConnections,
      maxMessages: 100,
      connectionTimeout: 10_000,
      greetingTimeout: 10_000,
      socketTimeout: 20_000,
      tls: { servername: this.config.host, rejectUnauthorized: true },
    });
    return this.transporter;
  }
}

function safeEmail(value: string, label: string): string {
  const email = value.trim().toLowerCase();
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) || email.length > 320 || /[\r\n]/.test(email)) throw new Error(`Invalid ${label} email`);
  return email;
}

function safeRazorpayUrl(value: string): string {
  const parsed = new URL(value);
  const trustedHost = /(^|\.)razorpay\.com$/i.test(parsed.hostname) || /(^|\.)rzp\.io$/i.test(parsed.hostname);
  if (parsed.protocol !== 'https:' || !trustedHost || parsed.username || parsed.password) throw new Error('Recovery email requires a verified Razorpay Payment Link URL');
  return parsed.toString();
}

function boundedText(value: string, maxLength: number, label: string): string {
  const text = value.trim().replace(/[\r\n]+/g, ' ');
  if (!text || text.length > maxLength) throw new Error(`${label} is invalid`);
  return text;
}

function renderText(copyIntent: string, url: string): string {
  const copy = boundedText(copyIntent, 600, 'Email copy intent');
  return `${copy}\n\nComplete your payment securely via Razorpay: ${url}\n\nThis recovery link was generated by PayScope AI after detecting an issue with your recent transaction. If you did not expect this email, you can safely ignore it.`;
}

function renderHtml(copyIntent: string, url: string): string {
  const copy = escapeHtml(boundedText(copyIntent, 600, 'Email copy intent'));
  const link = escapeHtml(url);
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Complete Your Payment — PayScope</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      background-color: #0c1021;
      margin: 0;
      padding: 0;
      color: #e2e8f0;
      -webkit-font-smoothing: antialiased;
    }
    .email-container {
      max-width: 600px;
      margin: 30px auto;
      background: #14192d;
      border: 1px solid rgba(255, 255, 255, 0.08);
      border-radius: 16px;
      overflow: hidden;
      box-shadow: 0 20px 40px rgba(0, 0, 0, 0.4);
    }
    .header {
      background: linear-gradient(135deg, #0c1021 0%, #1a2238 100%);
      padding: 32px 28px;
      text-align: center;
      border-bottom: 1px solid rgba(0, 255, 135, 0.15);
    }
    .brand-badge {
      display: inline-block;
      padding: 6px 14px;
      background: rgba(0, 255, 135, 0.1);
      border: 1px solid rgba(0, 255, 135, 0.3);
      border-radius: 9999px;
      color: #00ff87;
      font-size: 11px;
      font-weight: 700;
      letter-spacing: 0.1em;
      text-transform: uppercase;
      margin-bottom: 12px;
    }
    .header h1 {
      margin: 0;
      color: #ffffff;
      font-size: 24px;
      font-weight: 800;
      letter-spacing: -0.02em;
    }
    .content {
      padding: 36px 28px;
      background-color: #14192d;
    }
    .copy-box {
      font-size: 16px;
      line-height: 1.6;
      color: #cbd5e1;
      margin-bottom: 28px;
    }
    .cta-container {
      text-align: center;
      margin: 32px 0;
    }
    .cta-button {
      display: inline-block;
      padding: 16px 36px;
      background: linear-gradient(135deg, #00ff87 0%, #00d674 100%);
      color: #050811 !important;
      text-decoration: none !important;
      font-weight: 800;
      font-size: 16px;
      border-radius: 12px;
      box-shadow: 0 10px 25px rgba(0, 255, 135, 0.3);
      letter-spacing: 0.01em;
    }
    .security-banner {
      background: rgba(255, 255, 255, 0.03);
      border-left: 4px solid #00ff87;
      border-radius: 8px;
      padding: 16px 20px;
      margin: 28px 0;
    }
    .security-banner p {
      margin: 0;
      font-size: 13px;
      color: #94a3b8;
      line-height: 1.5;
    }
    .footer {
      padding: 24px 28px;
      background: #090d1b;
      border-top: 1px solid rgba(255, 255, 255, 0.05);
      text-align: center;
      color: #64748b;
      font-size: 12px;
      line-height: 1.6;
    }
  </style>
</head>
<body>
  <div class="email-container">
    <div class="header">
      <div class="brand-badge">⚡ PayScope Revenue Rescue</div>
      <h1>Complete Your Payment</h1>
    </div>
    <div class="content">
      <div class="copy-box">${copy}</div>
      <div class="cta-container">
        <a href="${link}" target="_blank" class="cta-button">Complete Payment via Razorpay ➔</a>
      </div>
      <div class="security-banner">
        <p><strong>🔒 Verified Razorpay Transaction</strong><br />This 1-click payment link is encrypted and generated directly via Razorpay checkout. Your payment is 100% secure.</p>
      </div>
    </div>
    <div class="footer">
      <p>This automated message was delivered by PayScope Autonomous Operations.<br />If you did not initiate this transaction, you can safely ignore this email.</p>
    </div>
  </div>
</body>
</html>`;
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]!));
}

function redactSmtpResponse(value: string): string {
  return value.replace(/[\r\n]+/g, ' ').replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi, '[REDACTED_EMAIL]').slice(0, 1_000);
}
