import { APP_CONFIG, apiUrl } from './config'
import type { AuditEntry, AuditIntegrity, DashboardMetrics, DashboardQueryResult, Incident, IncidentDetail, Investigation, MvpHealth, Proposal } from './types/mvp'

type Envelope<T> = { success: true; data: T } | { success: false; error?: { message?: string } }
type Guard<T> = (value: unknown) => value is T
type RequestOptions = { signal?: AbortSignal; failureMessage?: string }

/** One cancellation/timeout/error boundary for every browser-to-VPS request. */
async function request<T>(path: string, guard: Guard<T>, options: RequestOptions = {}): Promise<T> {
  const controller = new AbortController()
  let timedOut = false
  const abortFromCaller = () => controller.abort()
  options.signal?.addEventListener('abort', abortFromCaller, { once: true })
  const timeout = window.setTimeout(() => { timedOut = true; controller.abort() }, APP_CONFIG.apiTimeoutMs)
  try {
    const response = await fetch(apiUrl(path), { headers: { Accept: 'application/json' }, signal: controller.signal })
    const body = await response.json().catch(() => null) as Envelope<T> | null
    if (!response.ok || !body || body.success !== true) throw new Error(body && 'error' in body ? body.error?.message || options.failureMessage || 'Request failed' : options.failureMessage || 'Request failed')
    if (!guard(body.data)) throw new Error('The server returned an invalid MVP response. Refresh and try again if it persists.')
    return body.data
  } catch (error) {
    if (controller.signal.aborted) throw new Error(timedOut ? 'The API request timed out. Previous data, if any, is retained.' : 'The API request was cancelled.')
    throw error
  } finally { window.clearTimeout(timeout); options.signal?.removeEventListener('abort', abortFromCaller) }
}

export const mvpApi = {
  health: (signal?: AbortSignal) => request<MvpHealth>('/api/mvp/health', isHealth, { signal }),
  incidents: (status?: Incident['status'], signal?: AbortSignal) => request<Incident[]>(`/api/mvp/incidents?limit=100${status ? `&status=${encodeURIComponent(status)}` : ''}`, isIncidents, { signal }),
  incident: (id: string, signal?: AbortSignal) => request<IncidentDetail>(`/api/mvp/incidents/${encodeURIComponent(id)}`, isDetail, { signal }),
  audit: (incidentId: string, signal?: AbortSignal) => request<AuditEntry[]>(`/api/mvp/audit?incidentId=${encodeURIComponent(incidentId)}`, isAudits, { signal }),
  auditIntegrity: (signal?: AbortSignal) => request<AuditIntegrity>('/api/mvp/audit/integrity', isAuditIntegrity, { signal }),
  dashboardMetrics: (signal?: AbortSignal) => request<DashboardMetrics>('/api/mvp/dashboard/metrics', isDashboardMetrics, { signal }),
  dashboardQuery: (query: string, signal?: AbortSignal) => request<DashboardQueryResult>(`/api/mvp/dashboard/query?q=${encodeURIComponent(query)}&limit=10`, isDashboardQuery, { signal }),
}

const object = (value: unknown): Record<string, unknown> | null => value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : null
const text = (value: unknown): value is string => typeof value === 'string' && value.length > 0 && value.length <= 1_000
const amount = (value: unknown): value is number => typeof value === 'number' && Number.isSafeInteger(value) && value >= 0
const fraction = (value: unknown): value is number => typeof value === 'number' && Number.isFinite(value) && value >= 0 && value <= 1
const date = (value: unknown): value is string => text(value) && Number.isFinite(Date.parse(value))
const isIncident = (value: unknown): value is Incident => { const row = object(value); return Boolean(row && text(row.id) && text(row.organizationId) && ['CRITICAL', 'HIGH', 'MEDIUM', 'MONITOR'].includes(String(row.riskTier)) && ['OPEN', 'MONITORING', 'DISPUTE_OPENED', 'RESOLVED', 'DISMISSED'].includes(String(row.status)) && amount(row.totalFailedAmountPaise) && amount(row.recoveredAmountPaise) && amount(row.remainingAmountPaise) && row.remainingAmountPaise === row.totalFailedAmountPaise - row.recoveredAmountPaise && Array.isArray(row.correlatedEventIds) && row.correlatedEventIds.length <= 100 && row.correlatedEventIds.every(text) && date(row.openedAt) && (row.resolvedAt === null || date(row.resolvedAt)) && date(row.updatedAt)) }
const isHealth = (value: unknown): value is MvpHealth => { const row = object(value); return Boolean(row && text(row.organizationId) && row.pipeline === 'autonomous' && (row.razorpayEnvironment === 'test' || row.razorpayEnvironment === 'live') && ['autonomous_simulation', 'email_execution', 'email_execution_unavailable'].includes(String(row.communications)) && row.database === 'ready' && row.queueWorker === 'configured' && row.webhook === 'signed' && row.enrichmentAdapter === 'razorpay_fields_heuristic') }
const isIncidents = (value: unknown): value is Incident[] => Array.isArray(value) && value.length <= 100 && value.every(isIncident)
const isEvent = (value: unknown): boolean => {
  const row = object(value); const event = row && object(row.event); const enrichment = row?.enrichment
  const parsedEnrichment = object(enrichment)
  const validEnrichment = enrichment === null || Boolean(parsedEnrichment && ['razorpay_fields_heuristic', 'fixture_signed', 'vulcan_direct'].includes(String(parsedEnrichment.source)) && ['gateway_degraded', 'issuer_timeout', 'fraud_block', 'insufficient_funds', 'customer_drop', 'routing_suboptimal', 'unknown'].includes(String(parsedEnrichment.failureAttribution)) && typeof parsedEnrichment.gatewayHealthScore === 'number' && Number.isFinite(parsedEnrichment.gatewayHealthScore) && typeof parsedEnrichment.gatewayInDowntime === 'boolean' && typeof parsedEnrichment.downtimeScheduled === 'boolean' && typeof parsedEnrichment.crossBorderFlag === 'boolean' && amount(parsedEnrichment.priorAttemptCount) && typeof parsedEnrichment.partialRecoveryPossible === 'boolean' && (parsedEnrichment.recommendedRetryMethod === null || text(parsedEnrichment.recommendedRetryMethod)) && Array.isArray(parsedEnrichment.signalsUsed) && parsedEnrichment.signalsUsed.length <= 32 && parsedEnrichment.signalsUsed.every(text))
  return Boolean(row && text(row.id) && text(row.organizationId) && event && text(event.eventType) && date(event.occurredAt) && date(event.receivedAt) && (event.amountPaise === undefined || amount(event.amountPaise)) && (event.paymentMethod === undefined || text(event.paymentMethod)) && (row.enrichmentSource === null || ['razorpay_fields_heuristic', 'fixture_signed', 'vulcan_direct', 'unavailable'].includes(String(row.enrichmentSource))) && validEnrichment)
}
const isProposal = (value: unknown): value is Proposal => { const row = object(value); return Boolean(row && text(row.id) && text(row.organizationId) && text(row.incidentId) && text(row.actionType) && ['pending', 'simulated', 'cancelled_by_dispute', 'cancelled_by_recovery', 'failed'].includes(String(row.status)) && date(row.proposedAt) && (row.simulatedAt === null || date(row.simulatedAt)) && object(row.content) && (row.deliveryResult === null || object(row.deliveryResult))) }
const isExecutionAction = (value: unknown): value is import('./types/mvp').ExecutionActionSummary => { const row = object(value); return Boolean(row && text(row.id) && text(row.capability) && ['queued', 'dispatching', 'accepted', 'unreconciled', 'confirmed', 'retry_scheduled', 'compensating', 'failed', 'cancelled'].includes(String(row.state)) && (row.amountPaise === null || amount(row.amountPaise)) && (row.currency === null || text(row.currency)) && (row.terminalReason === null || text(row.terminalReason)) && (row.providerObjectId === null || text(row.providerObjectId)) && amount(row.retryCount) && text(row.policyVersion) && text(row.capabilityVersion) && date(row.createdAt) && (row.dispatchedAt === null || date(row.dispatchedAt)) && (row.completedAt === null || date(row.completedAt))) }
const isStructuredAction = (value: unknown): boolean => {
  const action = object(value)
  return Boolean(action && ['deliver_recovery_link_email', 'record_risk_signal', 'submit_dispute_evidence', 'capture_authorized_payment', 'refund_payment', 'resolve_infrastructure'].includes(String(action.actionType)) && text(action.rationale) && action.rationale.length <= 100 && Array.isArray(action.preconditions) && action.preconditions.length >= 1 && action.preconditions.length <= 6 && action.preconditions.every(item => text(item) && item.length <= 140) && text(action.expectedOutcome) && action.expectedOutcome.length <= 160 && (action.estimatedRecoveryPaise === null || amount(action.estimatedRecoveryPaise)) && (action.scriptContent === undefined || (text(action.scriptContent) && action.scriptContent.length <= 600)) && (action.emailCopyIntent === undefined || (text(action.emailCopyIntent) && action.emailCopyIntent.length <= 600)) && action.requiresAutonomousExecution === true)
}
const isInvestigation = (value: unknown): value is Investigation => {
  const row = object(value); const plan = row && object(row.plan); const risk = row && object(row.riskAnalysis); const recovery = row && object(row.recoveryPlan); const policy = row && object(row.policyDecision)
  const planValid = plan === null || Boolean(plan && text(plan.hypothesis) && ['infrastructure', 'fraud_suspected', 'fraud_confirmed', 'customer_error', 'subscription_issue', 'unknown'].includes(String(plan.primaryFailureCategory)) && Array.isArray(plan.objectives) && plan.objectives.length >= 1 && plan.objectives.length <= 4 && plan.objectives.every(text) && Array.isArray(plan.evidencePriorities) && plan.evidencePriorities.length >= 1 && plan.evidencePriorities.length <= 5 && plan.evidencePriorities.every(priority => { const item = object(priority); return Boolean(item && text(item.fact) && text(item.whyItMatters)) }) && Array.isArray(plan.subAgents) && plan.subAgents.length <= 2 && plan.subAgents.every(agent => { const item = object(agent); return Boolean(item && ['risk_analyst', 'recovery_planner'].includes(String(item.agent)) && text(item.question) && (item.priority === 1 || item.priority === 2) && Array.isArray(item.allowedContextFields) && item.allowedContextFields.length >= 1 && item.allowedContextFields.length <= 8 && item.allowedContextFields.every(text)) }) && Array.isArray(plan.constraints) && plan.constraints.length >= 1 && plan.constraints.length <= 6 && plan.constraints.every(text) && Array.isArray(plan.noActionCriteria) && plan.noActionCriteria.length >= 1 && plan.noActionCriteria.length <= 6 && plan.noActionCriteria.every(text) && typeof plan.requiresNoActionFallback === 'boolean' && typeof plan.estimatedAutoResolvable === 'boolean' && fraction(plan.confidence) && text(plan.reasoning))
  const tools = risk && object(risk.toolResults)
  const riskValid = risk === null || Boolean(risk && ['gateway_degraded', 'issuer_block', 'fraud_confirmed', 'fraud_suspected', 'customer_error', 'subscription_lapse', 'unknown'].includes(String(risk.failureRootCause)) && ['strong', 'moderate', 'weak'].includes(String(risk.evidenceStrength)) && fraction(risk.confidence) && text(risk.causalNarrative) && text(risk.evidenceConfidenceRationale) && Array.isArray(risk.alternativeHypotheses) && risk.alternativeHypotheses.length <= 3 && risk.alternativeHypotheses.every(text) && amount(risk.falsePositiveCostEstimatePaise) && Array.isArray(risk.missingEvidence) && risk.missingEvidence.length <= 12 && risk.missingEvidence.every(text) && typeof risk.chargebackEvidenceReady === 'boolean' && Array.isArray(risk.evidenceItems) && risk.evidenceItems.length <= 30 && risk.evidenceItems.every(text) && ['auto_resolve_no_action', 'submit_dispute_evidence', 'record_risk_signal', 'propose_recovery', 'escalate_fraud'].includes(String(risk.recommendedActionCategory)) && tools && amount(tools.incidentTimelineEventCount) && (tools.merchantFailureRate === null || fraction(tools.merchantFailureRate)) && (tools.networkFailureRate === null || fraction(tools.networkFailureRate)) && (tools.customerIncidentCount === null || amount(tools.customerIncidentCount)))
  const recoveryValid = recovery === null || Boolean(recovery && Array.isArray(recovery.proposedActions) && recovery.proposedActions.length <= 8 && recovery.proposedActions.every(isStructuredAction) && fraction(recovery.recoveryProbability) && fraction(recovery.confidence) && (recovery.noActionReason === undefined || text(recovery.noActionReason)))
  const policyValid = policy === null || Boolean(policy && ['auto_with_proposals', 'auto_no_action'].includes(String(policy.outcome)) && Array.isArray(policy.permittedActions) && policy.permittedActions.length <= 8 && policy.permittedActions.every(isStructuredAction) && (policy.noActionReason === null || text(policy.noActionReason)) && (policy.matchedPolicyId === null || text(policy.matchedPolicyId)) && Array.isArray(policy.gates) && policy.gates.length >= 6 && policy.gates.length <= 13 && policy.gates.every(gate => { const item = object(gate); return Boolean(item && ['fraud', 'dispute', 'auto_resolve_ceiling', 'critical_tier', 'contact_limits', 'merchant_policy', 'execution_capability', 'provider_health', 'amount_currency', 'consent_quiet_hours', 'emergency_pause', 'idempotency', 'retry_budget'].includes(String(item.name)) && ['passed', 'blocked', 'restricted', 'skipped'].includes(String(item.result)) && text(item.rationale) && item.rationale.length <= 160) }))
  return Boolean(row && text(row.id) && text(row.organizationId) && text(row.incidentId) && ['PENDING', 'RUNNING', 'COMPLETE', 'FAILED'].includes(String(row.status)) && planValid && riskValid && recoveryValid && policyValid && (row.modelId === null || text(row.modelId)) && (row.tokensUsed === null || amount(row.tokensUsed)) && (row.latencyMs === null || amount(row.latencyMs)) && date(row.startedAt) && (row.completedAt === null || date(row.completedAt)))
}
const isDetail = (value: unknown): value is IncidentDetail => { const row = object(value); return Boolean(row && isIncident(row.incident) && Array.isArray(row.events) && row.events.length <= 100 && row.events.every(isEvent) && Array.isArray(row.proposals) && row.proposals.length <= 100 && row.proposals.every(isProposal) && (row.investigation === null || isInvestigation(row.investigation)) && Array.isArray(row.execution) && row.execution.length <= 50 && row.execution.every(isExecutionAction)) }
const isAudits = (value: unknown): value is AuditEntry[] => Array.isArray(value) && value.length <= 200 && value.every(value => { const row = object(value); return Boolean(row && text(row.id) && text(row.organizationId) && (row.incidentId === null || text(row.incidentId)) && amount(row.sequenceNumber) && text(row.eventType) && ['system', 'legacy'].includes(String(row.actorType)) && text(row.actorId) && text(row.decision) && text(row.rationale) && (row.confidence === null || fraction(row.confidence)) && (row.enrichmentSource === null || text(row.enrichmentSource)) && date(row.createdAt)) })
const isAuditIntegrity = (value: unknown): value is AuditIntegrity => { const row = object(value); return Boolean(row && ['intact', 'broken'].includes(String(row.status)) && amount(row.entryCount) && date(row.checkedAt)) }
const isDashboardQuery = (value: unknown): value is DashboardQueryResult => {
  const row = object(value)
  const summaries = row?.incidents
  return Boolean(row && text(row.query) && text(row.interpretation) && amount(row.matchedIncidentCount) && amount(row.matchedRemainingAmountPaise) && Array.isArray(summaries) && summaries.length <= 20 && summaries.every(item => { const incident = object(item); return Boolean(incident && text(incident.id) && ['OPEN', 'MONITORING', 'DISPUTE_OPENED', 'RESOLVED', 'DISMISSED'].includes(String(incident.status)) && ['CRITICAL', 'HIGH', 'MEDIUM', 'MONITOR'].includes(String(incident.riskTier)) && amount(incident.remainingAmountPaise) && date(incident.updatedAt)) }) && Array.isArray(row.limitations) && row.limitations.length >= 2 && row.limitations.length <= 8 && row.limitations.every(text))
}
const nullableAmount = (value: unknown): boolean => value === null || amount(value)
const nullableFraction = (value: unknown): boolean => value === null || fraction(value)
const isDashboardMetrics = (value: unknown): value is DashboardMetrics => {
  const row = object(value); const operations = row && object(row.operations); const evaluation = row && object(row.evaluation)
  if (!operations || !evaluation || !nullableAmount(operations.totalAtRiskPaise) || !amount(operations.actionsDispatched) || !amount(operations.smtpAccepted) || !amount(operations.smtpRejected) || !amount(operations.unreconciledEmails) || !amount(operations.confirmedRecoveries) || !amount(operations.refunded) || !amount(operations.failedActions) || !amount(operations.retried) || !amount(operations.compensated) || !amount(operations.unresolvedReceipts) || !['not_run', 'available'].includes(String(evaluation.status)) || !(evaluation.split === null || evaluation.split === 'development' || evaluation.split === 'held_out') || !(evaluation.fixtureSetVersion === null || text(evaluation.fixtureSetVersion)) || !(evaluation.runAt === null || date(evaluation.runAt)) || !(evaluation.configurationHash === null || (typeof evaluation.configurationHash === 'string' && /^[a-f0-9]{64}$/.test(evaluation.configurationHash))) || !(evaluation.modelId === null || text(evaluation.modelId)) || !amount(evaluation.sampleCount) || !nullableFraction(evaluation.precision) || !nullableFraction(evaluation.recall) || !nullableFraction(evaluation.f1) || !nullableAmount(evaluation.falsePositiveCostPaise) || !Array.isArray(row.exceptions) || row.exceptions.length < 6 || row.exceptions.length > 10 || !row.exceptions.every(text)) return false
  const metadata = [evaluation.split, evaluation.fixtureSetVersion, evaluation.runAt, evaluation.configurationHash, evaluation.modelId, evaluation.precision, evaluation.recall, evaluation.f1, evaluation.falsePositiveCostPaise]
  return evaluation.status === 'not_run'
    ? evaluation.sampleCount === 0 && metadata.every(item => item === null)
    : evaluation.sampleCount > 0 && metadata.every(item => item !== null)
}
