import { Bot, CheckCircle2, ChevronRight, ClipboardCheck, Eye, FileWarning, RefreshCw, ShieldAlert, X } from 'lucide-react'
import { ActionType, IncidentDetail as IncidentDetailData } from '../../types/paymentOps'

const money = (paise: number, currency = 'INR') => { if (!Number.isFinite(paise)) return '—'; try { return new Intl.NumberFormat('en-IN', { style: 'currency', currency, maximumFractionDigits: 0 }).format(paise / 100) } catch { return `₹${(paise / 100).toFixed(0)}` } }
const stamp = (value: string) => { const d = new Date(value); return Number.isFinite(d.getTime()) ? new Intl.DateTimeFormat('en-IN', { hour: 'numeric', minute: '2-digit', day: 'numeric', month: 'short' }).format(d) : 'unknown time' }
const actionLabel: Record<ActionType, string> = { review_payment_method: 'Approve payment-method review', prepare_follow_up: 'Approve follow-up preparation', escalate: 'Escalate to finance', monitor: 'Move to monitoring', dismiss: 'Dismiss incident' }
const TIMELINE_EVENT_LIMIT = 12

export function IncidentDetail({ detail, loading, onClose, onInvestigate, onAction, actionPending }: { detail: IncidentDetailData | null; loading: boolean; onClose: () => void; onInvestigate: () => void; onAction: (type: ActionType) => void; actionPending: boolean }) {
  if (!detail && !loading) return <section className="flex min-h-[420px] items-center justify-center rounded-2xl border border-dashed border-white/15 bg-[#090a0f]/55 p-8 text-center"><div><Eye className="mx-auto h-7 w-7 text-neutral-500" /><p className="mt-3 text-sm font-semibold text-white">Open an incident to inspect it</p><p className="mx-auto mt-1 max-w-xs text-[10px] leading-relaxed text-neutral-500">The agent trace, verified evidence, and human controls stay attached to the incident that created them.</p></div></section>
  if (loading || !detail) return <section className="min-w-0 flex min-h-[420px] items-center justify-center rounded-2xl border border-white/[.09] bg-[#090a0f]/80 text-xs text-neutral-400"><RefreshCw className="mr-2 h-4 w-4 animate-spin" />Loading incident evidence…</section>
  const { incident, events, audit } = detail
  const run = incident.agentRun
  const visibleEvents = events.slice(0, TIMELINE_EVENT_LIMIT)
  const hiddenEventCount = Math.max(0, incident.eventCount - visibleEvents.length)
  return <section className="min-w-0 overflow-hidden rounded-2xl border border-white/[.09] bg-[#090a0f]/90"><header className="flex min-w-0 items-start justify-between border-b border-white/[.08] px-4 py-3"><div className="min-w-0"><p className="text-[9px] font-bold uppercase tracking-[.14em] text-[#b8ffd9]">Incident investigation</p><h2 className="mt-1 truncate text-sm font-bold text-white">{incident.title}</h2><p className="mt-1 truncate text-[10px] text-neutral-500">{incident.customerReference} · {incident.incidentId}</p></div><button type="button" onClick={onClose} aria-label="Close incident" className="shrink-0 rounded-lg border border-white/10 p-1.5 text-neutral-400 hover:bg-white/10 hover:text-white"><X className="h-3.5 w-3.5" /></button></header>
    <div className="grid min-w-0 gap-0 2xl:grid-cols-[minmax(0,1fr)_minmax(0,1.1fr)]"><div className="min-w-0 border-b border-white/[.08] p-4 2xl:border-b-0 2xl:border-r"><div className="grid grid-cols-2 gap-2"><Fact label="At risk" value={money(Math.max(0, incident.amountAtRiskPaise - incident.recoveredAmountPaise), incident.currency)} /><Fact label="Recovered" value={money(incident.recoveredAmountPaise, incident.currency)} /><Fact label="Verified events" value={String(incident.eventCount)} /><Fact label="Current status" value={incident.status.replace('_', ' ')} /></div><div className="mt-4 flex items-end justify-between gap-2"><h3 className="text-[10px] font-bold uppercase tracking-[.12em] text-neutral-400">Verified event timeline</h3><p className="text-right text-[10px] text-neutral-500">Newest {visibleEvents.length} of {incident.eventCount}</p></div><ol className="mt-2 space-y-2">{visibleEvents.map(event => <li key={event.eventId} className="min-w-0 rounded-xl border border-white/[.08] bg-black/15 p-2.5"><div className="flex min-w-0 items-start justify-between gap-2"><div className="min-w-0"><p className="text-[11px] font-bold text-white">{event.eventType}</p><p className="mt-0.5 break-all text-[10px] text-neutral-500">{event.eventId}</p></div><span className="shrink-0 rounded-full bg-sky-300/10 px-1.5 py-0.5 text-[9px] font-bold text-sky-100">{event.source === 'history_import' ? 'import' : 'verified'}</span></div><p className="mt-1.5 text-[11px] text-neutral-300">{event.summary}</p><p className="mt-1 text-[10px] text-neutral-500">{event.amountPaise !== undefined ? money(event.amountPaise, event.currency) : 'Amount unavailable'} · {stamp(event.occurredAt)}</p></li>)}</ol>{hiddenEventCount > 0 && <p className="mt-3 rounded-xl border border-dashed border-white/[.12] bg-black/10 px-3 py-2 text-[10px] leading-relaxed text-neutral-400">{hiddenEventCount} older verified event{hiddenEventCount === 1 ? '' : 's'} are retained in the incident but hidden here to keep the investigation readable.</p>}</div>
      <div className="min-w-0 p-4"><div className="flex min-w-0 items-center justify-between gap-2"><div className="flex min-w-0 items-center gap-2"><div className="shrink-0 rounded-xl border border-[#00ff87]/25 bg-[#00ff87]/10 p-1.5 text-[#00ff87]"><Bot className="h-4 w-4" /></div><div className="min-w-0"><h3 className="text-xs font-bold text-white">Agent investigation</h3><p className="text-[9px] text-neutral-500">Evidence-bound recommendation, not autonomous execution</p></div></div><button type="button" onClick={onInvestigate} disabled={actionPending} className="shrink-0 rounded-lg border border-white/10 px-2 py-1 text-[9px] font-semibold text-neutral-200 hover:bg-white/10 disabled:opacity-50"><RefreshCw className="mr-1 inline h-3 w-3" />Re-run</button></div>
        {run ? <div className="mt-3 space-y-3"><div className="rounded-xl border border-[#00ff87]/15 bg-[#00ff87]/[.045] p-3"><div className="flex items-center justify-between gap-2"><span className="text-[9px] font-bold uppercase tracking-wide text-[#b8ffd9]">{run.provider === 'model' ? 'Model investigation' : 'Rules investigation'}</span><span className="text-[9px] text-neutral-400">{Math.round(run.confidence * 100)}% confidence</span></div><p className="mt-2 text-[11px] font-medium leading-relaxed text-white">{run.incidentSummary}</p><p className="mt-2 text-[10px] leading-relaxed text-neutral-300">{run.observedPattern}</p></div><Evidence title="Evidence used" items={run.evidenceEventIds} /><Evidence title="Missing context" items={run.missingContext} muted /><div className="rounded-xl border border-sky-300/20 bg-sky-300/[.05] p-3"><p className="flex items-center gap-1.5 text-[10px] font-bold text-sky-100"><ClipboardCheck className="h-3.5 w-3.5" />Recommended next step</p><p className="mt-1 text-[11px] font-semibold text-white">{run.recommendedAction.type.replace(/_/g, ' ')}</p><p className="mt-1 text-[10px] leading-relaxed text-neutral-300">{run.recommendedAction.rationale}</p><p className="mt-2 text-[9px] text-sky-100">{typeof incident.operatorAction?.operator === 'string' && incident.operatorAction.operator.startsWith('agent:policy/') ? `Auto-executed by ${incident.operatorAction.operator} — governed by threshold policy.` : 'Human approval is required. No payment, refund, subscription, email, or customer message is triggered here.'}</p></div>{incident.status !== 'recovered' && incident.status !== 'dismissed' && <div className="grid gap-2 sm:grid-cols-2"><ActionButton type={run.recommendedAction.type} onAction={onAction} pending={actionPending} primary /><ActionButton type="dismiss" onAction={onAction} pending={actionPending} /></div>}</div> : <div className="mt-3 rounded-xl border border-dashed border-white/15 p-4 text-center"><FileWarning className="mx-auto h-5 w-5 text-amber-100" /><p className="mt-2 text-[10px] text-neutral-300">No investigation has completed yet.</p><button type="button" onClick={onInvestigate} className="mt-2 rounded-lg bg-[#00ff87] px-3 py-1.5 text-[10px] font-bold text-black">Run investigation</button></div>}
        <h3 className="mt-4 text-[10px] font-bold uppercase tracking-[.12em] text-neutral-400">Audit trail</h3><ol className="mt-2 space-y-2 border-l border-white/[.1] pl-3">{audit.map(item => <li key={item.auditId} className="relative text-[11px] leading-relaxed text-neutral-400"><span className="absolute -left-[17px] top-1.5 h-2 w-2 rounded-full border border-[#090a0f] bg-[#00ff87]" /><p><strong className="text-neutral-200">{item.action.replace(/_/g, ' ')}</strong> · {item.actor}</p><p>{item.detail}</p><p className="mt-0.5 text-[10px] text-neutral-600">{stamp(item.at)}</p></li>)}</ol></div></div>
  </section>
}

function Fact({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/[.08] bg-black/15 p-2.5"><p className="text-[8px] font-semibold uppercase tracking-[.12em] text-neutral-500">{label}</p><p className="mt-1 truncate text-[11px] font-bold capitalize text-white">{value}</p></div> }
function Evidence({ title, items, muted = false }: { title: string; items: string[]; muted?: boolean }) { return <div className="min-w-0"><p className="text-[9px] font-bold uppercase tracking-[.12em] text-neutral-400">{title}</p>{items.length ? <ul className="mt-1.5 space-y-1">{items.map(item => <li key={item} className={`flex min-w-0 gap-1.5 break-words text-[10px] leading-relaxed ${muted ? 'text-neutral-500' : 'text-neutral-300'}`}><ChevronRight className="mt-0.5 h-3 w-3 shrink-0 text-[#00ff87]" /><span className="min-w-0 break-all">{item}</span></li>)}</ul> : <p className="mt-1 text-[10px] text-neutral-500">None recorded.</p>}</div> }
function ActionButton({ type, onAction, pending, primary = false }: { type: ActionType; onAction: (type: ActionType) => void; pending: boolean; primary?: boolean }) { return <button type="button" onClick={() => onAction(type)} disabled={pending} className={`rounded-xl border px-3 py-2 text-[10px] font-bold transition-colors disabled:cursor-not-allowed disabled:opacity-50 ${primary ? 'border-[#00ff87]/30 bg-[#00ff87] text-black hover:bg-[#b8ffd9]' : 'border-white/10 bg-white/[.04] text-neutral-200 hover:bg-white/[.1]'}`}>{primary ? <CheckCircle2 className="mr-1 inline h-3.5 w-3.5" /> : <ShieldAlert className="mr-1 inline h-3.5 w-3.5" />}{actionLabel[type]}</button> }
