import { ArrowUpRight, Bot, CircleAlert, Clock3, ShieldCheck } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Incident, IncidentStatus } from '../../types/paymentOps'

const statusStyle: Record<IncidentStatus, string> = { needs_review: 'border-rose-400/30 bg-rose-400/10 text-rose-100', monitoring: 'border-amber-300/30 bg-amber-300/10 text-amber-100', recovered: 'border-[#00ff87]/30 bg-[#00ff87]/10 text-[#b8ffd9]', escalated: 'border-orange-400/30 bg-orange-400/10 text-orange-100', dismissed: 'border-white/10 bg-white/[0.04] text-neutral-400' }
const severityStyle = { critical: 'text-rose-200', high: 'text-amber-100', medium: 'text-sky-100', low: 'text-neutral-300' }
const money = (paise: number, currency = 'INR') => { if (!Number.isFinite(paise)) return '—'; try { return new Intl.NumberFormat('en-IN', { style: 'currency', currency, maximumFractionDigits: 0 }).format(paise / 100) } catch { return `₹${(paise / 100).toFixed(0)}` } }
const time = (value: string) => { const d = new Date(value); return Number.isFinite(d.getTime()) ? new Intl.DateTimeFormat('en-IN', { hour: 'numeric', minute: '2-digit', day: 'numeric', month: 'short' }).format(d) : 'unknown time' }

export function IncidentList({ incidents, activeId, onSelect, loading }: { incidents: Incident[]; activeId?: string; onSelect: (incident: Incident) => void; loading: boolean }) {
  const [showAll, setShowAll] = useState(false)
  const openIncidents = useMemo(() => incidents.filter(incident => ['needs_review', 'monitoring', 'escalated'].includes(incident.status)), [incidents])
  const visibleIncidents = showAll ? incidents : openIncidents
  return <section className="overflow-hidden rounded-2xl border border-white/[.09] bg-[#090a0f]/80"><header className="border-b border-white/[.08] px-4 py-3"><div className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-bold text-white">Incident queue</h2><p className="mt-0.5 text-[10px] text-neutral-500">Prioritized evidence for operator review</p></div><span className="shrink-0 rounded-full border border-white/10 bg-white/[.04] px-2 py-1 text-[9px] font-semibold text-neutral-300">{visibleIncidents.length} shown</span></div><div className="mt-3 grid grid-cols-2 gap-1 rounded-lg border border-white/[.08] bg-black/15 p-1"><button type="button" aria-pressed={!showAll} onClick={() => setShowAll(false)} className={`rounded-md px-2 py-1 text-[9px] font-semibold transition-colors ${!showAll ? 'bg-[#00ff87]/15 text-[#b8ffd9]' : 'text-neutral-500 hover:text-neutral-300'}`}>Needs attention ({openIncidents.length})</button><button type="button" aria-pressed={showAll} onClick={() => setShowAll(true)} className={`rounded-md px-2 py-1 text-[9px] font-semibold transition-colors ${showAll ? 'bg-white/[.08] text-white' : 'text-neutral-500 hover:text-neutral-300'}`}>All incidents ({incidents.length})</button></div></header>
    <div className="max-h-[520px] overflow-y-auto" data-scrollable="true">{loading ? <p className="p-6 text-center text-xs text-neutral-500">Loading payment incidents…</p> : visibleIncidents.length === 0 ? <div className="p-6 text-center"><ShieldCheck className="mx-auto h-6 w-6 text-[#00ff87]" /><p className="mt-2 text-xs font-semibold text-white">{showAll ? 'No incidents recorded yet' : 'No incidents need attention'}</p><p className="mt-1 text-[10px] leading-relaxed text-neutral-500">{showAll ? 'Verified payment incidents will appear here as Razorpay signals arrive.' : 'Open the all-incidents view to inspect resolved work, or wait for the next verified payment signal.'}</p></div> : visibleIncidents.map(incident => <button key={incident.incidentId} type="button" onClick={() => onSelect(incident)} className={`group w-full border-b border-white/[.06] px-4 py-3 text-left transition-colors last:border-none hover:bg-white/[.035] ${activeId === incident.incidentId ? 'bg-[#00ff87]/[.06]' : ''}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-1.5"><span className={`text-[10px] font-bold uppercase ${severityStyle[incident.severity]}`}>{incident.severity}</span><span className={`rounded-full border px-1.5 py-0.5 text-[9px] font-bold ${statusStyle[incident.status]}`}>{incident.status.replace('_', ' ')}</span></div><p className="mt-1 truncate text-xs font-bold text-white">{incident.title}</p><p className="mt-0.5 truncate text-[10px] text-neutral-400">{incident.customerReference} {incident.paymentMethod ? `· ${incident.paymentMethod}` : ''}</p></div><ArrowUpRight className="mt-1 h-4 w-4 shrink-0 text-neutral-500 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-white" /></div><div className="mt-2 flex items-center justify-between gap-2"><span className="text-[11px] font-semibold text-white">{money(Math.max(0, incident.amountAtRiskPaise - incident.recoveredAmountPaise), incident.currency)}</span><span className="flex items-center gap-1 text-[9px] text-neutral-500"><Clock3 className="h-3 w-3" />{time(incident.latestEventAt)}</span></div>{incident.agentRun && <p className="mt-2 flex items-center gap-1.5 text-[9px] leading-relaxed text-neutral-400"><Bot className="h-3 w-3 text-[#00ff87]" />{incident.agentRun.recommendedAction.type.replace(/_/g, ' ')} · {Math.round(incident.agentRun.confidence * 100)}% confidence</p>}{incident.status === 'escalated' && <p className="mt-2 flex items-center gap-1 text-[9px] text-orange-200"><CircleAlert className="h-3 w-3" />Escalated for human review</p>}</button>)}</div>
  </section>
}
